tasks:
  - source: pgn_to_xlan.py
    product:
      nb: output/pgn_to_xlan.ipynb
      data: data/xlan/carlsen.xlanplus

  - source: create_tokens.py
    product:
      nb: output/create_tokens.ipynb
      data: data/tokens//carlsen.tok

  - source: remove_lines.py
    product:
      nb: output/remove_lines.ipynb
      data: data/tokens/carlsen_max_768.tok
