tasks:
  - source: ./pipeline/pgn_to_xlan.py
    product:
      nb: ./pipeline/output/pgn_to_xlan.ipynb
      data: ./pipeline/data_artifacts/xlan/{{chess_player}}.xlanplus
    params:
      pgn_path: ./pipeline/input_data/{{chess_player}}.pgn
      lan_path: ./pipeline/data_artifacts/xlan/{{chess_player}}.xlanplus
      training_file: ./pipeline/data_artifacts/xlan/{{chess_player}}.xlanplus

  - source: ./pipeline/create_tokens.py
    product:
      nb: ./pipeline/output/create_tokens.ipynb
      data: ./pipeline/data_artifacts/tokens/{{chess_player}}.tok
    params:
      xLAN_path: ./pipeline/data_artifacts/xlan/{{chess_player}}.xlanplus
      token_path: ./src/tokenizer/xlanplus_tokens.json
      tokenized_path: ./pipeline/data_artifacts/tokens/{{chess_player}}.tok

  - source: ./pipeline/remove_lines.py
    product:
      nb: ./pipeline/output/remove_lines.ipynb
      data: ./pipeline/data_artifacts/tokens/{{chess_player}}_max_768.tok
    params:
      input_file_path: ./pipeline/data_artifacts/tokens/{{chess_player}}.tok
      output_file_path: ./pipeline/data_artifacts/tokens/{{chess_player}}_max_768.tok

  - source: ./pipeline/add_bos.py
    product:
      nb: ./pipeline/output/add_tokens.ipynb
      data: ./pipeline/data_artifacts/tokens/{{chess_player}}_max_768_bos.tok
    params:
      text_file_in: ./pipeline/data_artifacts/tokens/{{chess_player}}_max_768.tok
      text_file_out: ./pipeline/data_artifacts/tokens/{{chess_player}}_max_768_bos.tok

  - source: ./pipeline/finetune.py
    product:
      nb: ./pipeline/output/finetune.ipynb
    params:
      chess_player: '{{chess_player}}'
      dataset: ./pipeline/data_artifacts/tokens/{{chess_player}}_max_768_bos.tok
